SPEC=Sstc
VERSION=1.0.0
STAGE=Ratified

COMMITDATE=$(shell git show -s --format=%ci | cut -d ' ' -f 1)
GITVERSION=$(shell git describe --tags --always --dirty)

GENDIR=autogenerated

SPEC_PDF=$(GENDIR)/$(SPEC).pdf

all: $(SPEC_PDF)

REVISION_SRC=$(GENDIR)/revision.adoc

HEADER_SRC=book_header.adoc

COMMON_SRCS= \
	bibliography.adoc \
	colophon.adoc \
	index.adoc \
	$(HEADER_SRC) \
	$(REVISION_SRC)

SPEC_SRCS=content.adoc

$(GENDIR):
	-mkdir $@

# Always perform this, but the rule is implemented so as to not touch the
# output if it needn't change.
.PHONY: $(REVISION_SRC)
$(REVISION_SRC): Makefile $(GENDIR)
	echo ":revdate: ${COMMITDATE}" > $@-tmp
	echo ":revnumber: ${VERSION}-${GITVERSION}" >> $@-tmp
	echo ":revremark: ${STAGE}" >> $@-tmp
	diff $@ $@-tmp || mv $@-tmp $@

# In order to remove the PHONY, this needs dependencies on all the input data,
# adocs, images/, resources/, etc.
.PHONY: $(SPEC_PDF)
$(SPEC_PDF): $(COMMON_SRCS) $(SPEC_SRCS) $(GENDIR)
	asciidoctor-pdf \
		--attribute=mathematical-format=svg \
		--attribute=pdf-fontsdir=resources/fonts \
		--attribute=pdf-style=resources/themes/risc-v_spec-pdf.yml \
		--failure-level=ERROR \
		--out-file=$@ \
		--require=asciidoctor-bibtex \
		--require=asciidoctor-diagram \
		--require=asciidoctor-mathematical \
		--trace \
		--verbose \
		$(HEADER_SRC)

clean:
	$(RM) -r $(GENDIR)
