SPEC=Sstc
VERSION=0.5.4
STAGE=frozen
COMMITDATE=$(shell git show -s --format=%ci | cut -d ' ' -f 1)
GITVERSION=$(shell git describe --tags --always --dirty)

GENDIR=autogenerated

SPEC_PDF=$(GENDIR)/$(SPEC).pdf

all: $(SPEC_PDF)

REVISION_SRC=$(GENDIR)/revision.adoc

HEADER_SRC=book_header.adoc

COMMON_SRCS= \
	bibliography.adoc \
	colophon.adoc \
	index.adoc \
	$(HEADER_SRC) \
	$(REVISION_SRC)

SPEC_SRCS=content.adoc

$(GENDIR):
	-mkdir $@

$(REVISION_SRC): Makefile $(GENDIR) FORCE
	echo ":revdate: ${COMMITDATE}" > $@-tmp
	echo ":revnumber: ${VERSION}-${GITVERSION}" >> $@-tmp
	echo ":revremark: ${STAGE}" >> $@-tmp
	diff $@ $@-tmp || mv $@-tmp $@

$(SPEC_PDF): $(COMMON_SRCS) $(SPEC_SRCS) $(GENDIR)
	asciidoctor-pdf \
		-v \
		-a mathematical-format=svg \
		-a pdf-style=resources/themes/risc-v_spec-pdf.yml \
		-a pdf-fontsdir=resources/fonts \
		$(HEADER_SRC) \
		-o $@

clean:
	$(RM) -r $(GENDIR)

.PHONY: FORCE
FORCE:
